namespace JanLenoch.CognitiveServices.Ocr
{
    public enum OcrLanguages
    {
        NotSet,
        AutoDetect,
        ChineseSimplified,
        ChineseTraditional,
        Czech,
        Danish,
        Dutch,
        English,
        Finnish,
        French,
        German,
        Greek,
        Hungarian,
        Italian,
        Japanese,
        Korean,
        Norwegian,
        Polish,
        Portuguese,
        Russian,
        Spanish,
        Swedish,
        Turkish
    }
}